const ACTIONS_TYPES = {
	API_PRODUCTS_PENDING: 'API_PENDING',
	API_PRODUCTS_SUCCESS: 'API_SUCCESS',
	API_PRODUCTS_ERROR: 'API_ERROR',
	ADD_PRODUCT: 'ADD_PRODUCT',
	EMPTY_CART: 'EMPTY_CART',
	SET_CART: 'SET_CART'
};
export default ACTIONS_TYPES;