const ACTIONS_TYPES = {
	API_PRODUCTS_PENDING: 'API_PENDING',
	API_PRODUCTS_SUCCESS: 'API_SUCCESS',
	API_PRODUCTS_ERROR: 'API_ERROR',
	SELECTION_PRODUCT: 'SELECTION_PRODUCT'
};
export default ACTIONS_TYPES;